ALTER TABLE passenger
    ADD COLUMN phone_number VARCHAR(255) NOT NULL,
    ADD COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN password VARCHAR(255) NOT NULL,
    MODIFY name VARCHAR(255) NOT NULL;